apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/your-username/your-private-repo.git
  username: <your-github-username>
  password: <your-personal-access-token> 